"""Testing rules — test presence and framework usage."""

import ast
import pathlib
import re
from collections.abc import Iterator
from typing import Any

from .. import _ast, _toml, _yaml
from .. import _models as models
from ._base import Rule


class NoUnitTests(Rule):
    """Check for the presence of unit tests."""

    category = "TESTING"
    number = 1
    name = "no-unit-tests"
    description = "No unit tests found in tests/unit/ or unit_tests/"
    default_severity = models.Severity.WARNING

    def check(self, context: models.CharmContext) -> list[models.Diagnostic]:
        # has_tests_unit is populated by _linter._check_tests.
        if not context.has_tests_unit:
            return [self.diagnostic(self.description, path="tests/unit/")]
        return []


class UsesHarness(Rule):
    """Detect unit tests written against the deprecated ``Harness``.

    ``tests/unit/`` and the rest of the test tree are examined, but not
    ``tests/integration/``: a charm with a flat ``tests/`` keeps its unit
    tests at the top level, and shared fixtures live in
    ``tests/conftest.py`` whichever layout is used. Integration tests
    drive a real deployment rather than either testing API, and a
    vendored library's own tests are its author's problem.

    One finding per test module, anchored at the first mention, rather
    than one per ``Harness(...)`` call: a suite that uses Harness uses it
    everywhere, and the migration is per-file work.
    """

    category = "TESTING"
    number = 3
    name = "uses-harness"
    description = "Unit tests use the deprecated ops.testing.Harness"
    default_severity = models.Severity.WARNING
    reference_url = (
        "https://canonical.com/juju/docs/ops/latest/howto/migrate/migrate-unit-tests-from-harness/"
    )

    def check(self, context: models.CharmContext) -> list[models.Diagnostic]:
        diagnostics: list[models.Diagnostic] = []
        for module in context.modules(models.Scope.TESTS_UNIT, models.Scope.TESTS_OTHER):
            line = _harness_line(module)
            if line is None:
                continue
            diagnostics.append(
                self.diagnostic(
                    "Unit tests use ops.testing.Harness, which is deprecated "
                    "— use the ops.testing state-transition API instead",
                    path=module.path,
                    line=line,
                    fix_hint="Rewrite the test with ops.testing.Context and ops.testing.State",
                )
            )
        return diagnostics


class UsesOpsScenario(Rule):
    """Detect tests that depend on the standalone ``ops-scenario`` package.

    Scenario moved into ops as ``ops.testing`` in ops 2.17, and the
    standalone package, imported as ``scenario``, is the form it took
    before the move. Two things are reported, each where it would be
    fixed:

    * a declaration of ``ops-scenario`` in ``pyproject.toml``, in a
      requirements file at the top of the charm, or in the ``deps`` of a
      ``tox.ini`` or ``tox.toml`` env;
    * a test module that imports ``scenario``, once per module, anchored
      at the first import. The test tree is examined as for TESTING-003,
      ``tests/integration/`` excepted.

    ``ops[testing]`` is the replacement, so it never matches, and nor
    does a package whose name only contains "scenario". A requirements
    file generated by ``pip-compile`` or ``uv pip compile`` is skipped:
    it lists ``ops-scenario`` because ``ops[testing]`` pulls it in, and
    the declaration to change is in the file it was compiled from.
    """

    category = "TESTING"
    number = 4
    name = "uses-ops-scenario"
    description = "Tests depend on the standalone ops-scenario package"
    default_severity = models.Severity.WARNING
    reference_url = "https://canonical.com/juju/docs/ops/latest/reference/ops-testing/"

    def check(self, context: models.CharmContext) -> list[models.Diagnostic]:
        diagnostics = [
            self.diagnostic(
                f"ops-scenario is declared{where} — the standalone package is "
                "the pre-ops 2.17 form of ops.testing",
                path=path,
                line=line,
                fix_hint="Depend on ops[testing] instead",
            )
            for path, line, where in _scenario_declarations(context)
        ]
        for module in context.modules(models.Scope.TESTS_UNIT, models.Scope.TESTS_OTHER):
            line = _scenario_import_line(module)
            if line is None:
                continue
            diagnostics.append(
                self.diagnostic(
                    "Tests import the standalone scenario package — since ops 2.17 "
                    "its API is ops.testing",
                    path=module.path,
                    line=line,
                    fix_hint="Import from ops.testing instead, e.g. `from ops import testing`",
                )
            )
        return diagnostics


# The deprecated class, spelled canonically. Every spelling a charm might
# use — ``ops.testing.Harness``, ``from ops.testing import Harness``,
# ``from ops import testing`` then ``testing.Harness`` — resolves to this
# through the module's import table, so the rule matches meaning rather
# than text.
_HARNESS = "ops.testing.Harness"


def _harness_line(module: models.Module) -> int | None:
    """Return the first line of *module* that refers to ``Harness``.

    ``None`` when the module does not use it. Both name chains and bare
    names are resolved through the import table, so a local class that
    happens to be called ``Harness`` does not match: without an import
    binding the name, it resolves to itself.
    """
    imports = _ast.Imports.of(module)
    lines = [
        node.lineno
        for node in module.walk(ast.Name, ast.Attribute)
        if imports.resolve(node) == _HARNESS
    ]
    return min(lines) if lines else None


# PEP 503 normalised, so ``ops_scenario`` and ``Ops.Scenario`` match too.
_OPS_SCENARIO = "ops-scenario"


def _scenario_declarations(
    context: models.CharmContext,
) -> Iterator[tuple[str, int | None, str]]:
    """Yield ``(path, line, where)`` for each file that declares ``ops-scenario``.

    One finding per file, anchored at the first declaring line. For the
    TOML files ``tomllib`` keeps no positions, so the finding anchors to
    the file and *where* names the sections instead; it is empty
    otherwise.
    """
    if context.pyproject is not None:
        sections = _pyproject_sections(context.pyproject)
        if sections:
            yield "pyproject.toml", None, _where(sections)
    requirements = {
        *context.charm_dir.glob("*requirements*.txt"),
        *context.charm_dir.glob("*requirements*.in"),
    }
    for path in sorted(requirements):
        line = _requirements_line(path)
        if line is not None:
            yield path.name, line, ""
    line = _tox_ini_line(context.charm_dir / "tox.ini")
    if line is not None:
        yield "tox.ini", line, ""
    sections = _tox_toml_sections(context.charm_dir / "tox.toml")
    if sections:
        yield "tox.toml", None, _where(sections)


def _pyproject_sections(data: dict[str, Any]) -> list[str]:
    """Return the dotted names of the ``pyproject.toml`` sections declaring it."""
    found: list[str] = []
    project = data.get("project")
    if isinstance(project, dict):
        if _declares(project.get("dependencies")):
            found.append("project.dependencies")
        optional = project.get("optional-dependencies")
        if isinstance(optional, dict):
            found.extend(
                f"project.optional-dependencies.{name}"
                for name, entries in optional.items()
                if _declares(entries)
            )
    groups = data.get("dependency-groups")
    if isinstance(groups, dict):
        found.extend(
            f"dependency-groups.{name}" for name, entries in groups.items() if _declares(entries)
        )
    tool = data.get("tool")
    poetry = tool.get("poetry") if isinstance(tool, dict) else None
    if isinstance(poetry, dict):
        tables = {
            f"tool.poetry.{key}": poetry.get(key) for key in ("dependencies", "dev-dependencies")
        }
        poetry_groups = poetry.get("group")
        if isinstance(poetry_groups, dict):
            tables.update(
                (f"tool.poetry.group.{name}.dependencies", group.get("dependencies"))
                for name, group in poetry_groups.items()
                if isinstance(group, dict)
            )
        found.extend(
            section
            for section, table in tables.items()
            if isinstance(table, dict) and any(_normalise(name) == _OPS_SCENARIO for name in table)
        )
    return found


def _declares(entries: Any) -> bool:
    """Whether a list of PEP 508 requirement strings includes ``ops-scenario``."""
    if not isinstance(entries, list):
        return False
    return any(
        isinstance(entry, str) and _requirement_name(entry) == _OPS_SCENARIO for entry in entries
    )


_REQUIREMENT_NAME = re.compile(r"\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def _requirement_name(requirement: str) -> str | None:
    """Return the normalised distribution name a PEP 508 requirement names."""
    match = _REQUIREMENT_NAME.match(requirement)
    return _normalise(match.group(1)) if match else None


def _normalise(name: str) -> str:
    """PEP 503 name normalisation — runs of ``-_.`` collapse, and case folds."""
    return re.sub(r"[-_.]+", "-", name).lower()


def _where(sections: list[str]) -> str:
    """Name the sections a declaration was found in, for a message."""
    return " in " + ", ".join(f"`{section}`" for section in sections)


def _requirements_line(path: pathlib.Path) -> int | None:
    """Return the line of a requirements file that declares ``ops-scenario``.

    ``None`` when no line does, or when the file was generated by
    ``pip-compile`` or ``uv pip compile``: both say ``autogenerated`` in
    the header, and both list every transitive dependency, so the file
    names ``ops-scenario`` whenever its source declares ``ops[testing]``.
    """
    try:
        lines = path.read_text().splitlines()
    except (OSError, UnicodeDecodeError):
        return None
    if any(line.startswith("#") and "autogenerated" in line.lower() for line in lines[:5]):
        return None
    for lineno, raw in enumerate(lines, start=1):
        requirement = raw.split("#", 1)[0].strip()
        if requirement and _requirement_name(requirement) == _OPS_SCENARIO:
            return lineno
    return None


# A tox.ini factor condition on a dependency, as in ``unit: ops-scenario``.
# Requiring whitespace after the colon keeps ``https://`` from matching.
_TOX_FACTOR = re.compile(r"^[A-Za-z0-9_.,!-]+:\s+")


def _tox_ini_line(path: pathlib.Path) -> int | None:
    """Return the first line of a ``tox.ini`` ``deps`` value that is ``ops-scenario``.

    ``deps`` holds one requirement per line, on the key's own line or
    indented below it. Anything outside a ``deps`` value, such as a
    ``commands`` line or a comment, is ignored.
    """
    try:
        lines = path.read_text().splitlines()
    except (OSError, UnicodeDecodeError):
        return None
    in_deps = False
    for lineno, raw in enumerate(lines, start=1):
        value = raw.strip()
        if not value or value[0] in "#;":
            continue
        if value.startswith("["):
            in_deps = False
            continue
        if raw[0] not in " \t":
            key, separator, value = raw.partition("=")
            in_deps = bool(separator) and key.strip() == "deps"
        if not in_deps:
            continue
        requirement = _TOX_FACTOR.sub("", value.split(" #", 1)[0].strip())
        if requirement and _requirement_name(requirement) == _OPS_SCENARIO:
            return lineno
    return None


def _tox_toml_sections(path: pathlib.Path) -> list[str]:
    """Return the ``tox.toml`` tables whose ``deps`` declare ``ops-scenario``."""
    try:
        data = _toml.load(path)
    except _yaml.FileLoadError:
        return []
    if data is None:
        return []
    tables: dict[str, Any] = {name: data.get(name) for name in ("env_run_base", "env_pkg_base")}
    envs = data.get("env")
    if isinstance(envs, dict):
        tables.update((f"env.{name}", env) for name, env in envs.items())
    return [
        f"{name}.deps"
        for name, table in tables.items()
        if isinstance(table, dict) and _declares(table.get("deps"))
    ]


def _scenario_import_line(module: models.Module) -> int | None:
    """Return the first line of *module* that imports ``scenario``, or ``None``.

    A submodule counts (``from scenario.state import State``). A relative
    import never does: ``from . import scenario`` is the charm's own
    module.
    """
    lines: list[int] = []
    for node in module.walk(ast.Import, ast.ImportFrom):
        if isinstance(node, ast.Import):
            names = [alias.name for alias in node.names]
        elif node.level == 0 and node.module:
            names = [node.module]
        else:
            continue
        if any(name.partition(".")[0] == "scenario" for name in names):
            lines.append(node.lineno)
    return min(lines) if lines else None
