"""Generate ``docs/rules.md``, the reference page for every registered rule.

The rules already carry everything the page needs — ID, name, category,
default severity, one-line description, reference URL, and a class
docstring saying what the rule looks for and why. This walks the registry
and lays that out as one Markdown page, so the published reference cannot
drift from the code the way a hand-maintained table does.

Usage::

    uv run python tools/generate_rules_doc.py            # rewrite the page
    uv run python tools/generate_rules_doc.py --check    # CI: fail if stale

``--check`` exits 1 when the generated text differs from what is on disk,
and prints the command to run. That is what CI calls.

The docstrings are written in the same reStructuredText-flavoured style as
the rest of the source, so ``double backticks`` are rewritten to Markdown's
single ones on the way out, a cross-reference role (``:data:`NAME```) becomes
a plain code span, and the ``::`` that introduces a literal block becomes a
single colon (the indented block is already code in Markdown). Everything
else — paragraphs, ``*emphasis*`` — is already Markdown as it stands.
"""

from __future__ import annotations

import argparse
import difflib
import inspect
import pathlib
import re
import sys

from charmlint._models import Severity
from charmlint._rules import Rule, get_all_rules

_ROOT = pathlib.Path(__file__).resolve().parent.parent
_OUTPUT = _ROOT / "docs" / "rules.md"
_ID_SCHEME = _ROOT / "docs" / "id-scheme.md"

_BANNER = (
    "<!-- Generated by tools/generate_rules_doc.py — do not edit by hand.\n"
    "     Run `make docs` after changing a rule. -->"
)

_PREAMBLE = """\
# charmlint rules

Every rule charmlint ships, in rule-ID order within each category. Each
entry gives the rule's ID, its name, the severity it reports at by
default, and what it checks for.

Anywhere charmlint accepts a rule — `select`, `ignore` and
`per-rule-severity` in `charmlint.toml`, `--select` and `--ignore` on the
command line, and the codes inside a suppression comment — the ID
(`SECURITY-001`), the name (`secret-in-plain-config`) and the category
(`SECURITY`) are all accepted. See the [README](../README.md) for
configuration and suppression, and [id-scheme.md](id-scheme.md) for how
IDs and names are assigned.

Severity is what the rule reports *by default*; `per-rule-severity` in the
config file overrides it per rule.
"""

_SEVERITY_LABELS = {
    Severity.ERROR: "Error",
    Severity.WARNING: "Warning",
    Severity.INFO: "Info",
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate docs/rules.md from the rule registry.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit non-zero if the page on disk is out of date",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=pathlib.Path,
        default=_OUTPUT,
        help=f"Where to write the page (default: {_OUTPUT.relative_to(_ROOT)})",
    )
    args = parser.parse_args(argv)

    generated = render(get_all_rules(), category_scopes(_ID_SCHEME))
    if not args.check:
        args.output.write_text(generated, encoding="utf-8")
        print(f"Wrote {args.output} ({len(get_all_rules())} rules)")
        return 0

    current = args.output.read_text(encoding="utf-8") if args.output.is_file() else ""
    if current == generated:
        return 0
    diff = difflib.unified_diff(
        current.splitlines(keepends=True),
        generated.splitlines(keepends=True),
        fromfile=f"{args.output} (on disk)",
        tofile=f"{args.output} (generated)",
    )
    sys.stdout.writelines(diff)
    print(
        f"\n{args.output} is out of date. "
        f"Run `make docs` (or `uv run python tools/generate_rules_doc.py`) and commit the result.",
        file=sys.stderr,
    )
    return 1


def render(rules: dict[str, Rule], scopes: dict[str, str]) -> str:
    """Return the whole page for *rules*, categories described by *scopes*."""
    by_category: dict[str, list[Rule]] = {}
    for rule in sorted(rules.values(), key=lambda r: (r.category, r.number)):
        by_category.setdefault(rule.category, []).append(rule)

    missing = sorted(set(by_category) - set(scopes))
    if missing:
        raise SystemExit(
            f"Categories missing from the catalogue in {_ID_SCHEME.relative_to(_ROOT)}: "
            f"{', '.join(missing)}"
        )

    parts = [_BANNER, "", _PREAMBLE, summary(by_category)]
    for category, category_rules in by_category.items():
        parts.append(f"## {category}\n\n{scopes[category]}.\n")
        parts.extend(entry(rule) for rule in category_rules)
    return "\n".join(parts).rstrip("\n") + "\n"


def summary(by_category: dict[str, list[Rule]]) -> str:
    """Return the table listing every rule, linked to its entry."""
    lines = [
        "## Summary",
        "",
        "| Rule | Name | Severity | Checks for |",
        "| --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| [{rule.id}](#{anchor(rule)}) | `{rule.name}` "
        f"| {_SEVERITY_LABELS[rule.default_severity]} | {cell(rule.description)} |"
        for rules in by_category.values()
        for rule in rules
    )
    lines.append("")
    return "\n".join(lines)


def anchor(rule: Rule) -> str:
    """Return the in-page anchor for *rule*'s heading, GitHub-style."""
    return f"{rule.id}-{rule.name}".lower()


def cell(text: str) -> str:
    """Return *text* safe to drop into a Markdown table cell."""
    return markdown(text).replace("|", "\\|")


def markdown(text: str) -> str:
    """Return *text* with the source's RST inline markup as Markdown.

    ``double backticks`` become single ones; a run that wraps across a
    source line is joined back onto one, so the Markdown code span holds
    the spelling the docstring meant rather than a newline. A role such as
    ``:data:`NAME``` is a cross-reference Markdown can't follow, so it is
    shown as the code span it names. A paragraph ending in ``::`` ends in a
    colon instead (``text ::``, with a space, in nothing).
    """
    text = re.sub(r":[a-z]+:`~?([^`]+)`", r"`\1`", text)
    text = re.sub(r"(\S)::$", r"\1:", text, flags=re.M)
    text = re.sub(r"\s+::$", "", text, flags=re.M)
    return re.sub(r"``(.+?)``", lambda m: f"`{' '.join(m.group(1).split())}`", text, flags=re.S)


def entry(rule: Rule) -> str:
    """Return the section documenting one rule."""
    lines = [
        f"### {rule.id} {rule.name}",
        "",
        f"**{_SEVERITY_LABELS[rule.default_severity]}** — {markdown(rule.description)}",
        "",
    ]
    body = explanation(rule)
    if body:
        lines.extend([body, ""])
    if rule.reference_url:
        lines.extend([f"Reference: <{rule.reference_url}>", ""])
    return "\n".join(lines)


def explanation(rule: Rule) -> str:
    """Return the rule's docstring as Markdown prose, or ``""`` for none.

    The docstring is the rule author's account of what the rule looks for
    and what it deliberately stays quiet about, which is the part of the
    reference a user cannot reconstruct from a one-line description. Rules
    that have no docstring of their own contribute nothing here rather than
    inheriting the base class's.
    """
    docstring = rule.__class__.__doc__
    if not docstring or not docstring.strip():
        return ""
    return markdown(inspect.cleandoc(docstring))


def category_scopes(path: pathlib.Path) -> dict[str, str]:
    """Return each category's one-line scope, from the catalogue table.

    The table in ``docs/id-scheme.md`` is the prose half of the catalogue
    that ``charmlint._rules.CATEGORIES`` holds in code, so the headings on
    this page say the same thing about a category that the scheme does.
    """
    row = re.compile(r"^\|\s*([A-Z]+)\s*\|\s*(.+?)\s*\|$")
    matches = (row.match(line) for line in path.read_text(encoding="utf-8").splitlines())
    return {m.group(1): m.group(2) for m in matches if m}


if __name__ == "__main__":
    sys.exit(main())
